---
- hosts: all
  become: true
  tasks:
     - name: enable i2c module
       lineinfile: path=/etc/modules line='i2c-dev'
       
     - name: enable i2c module
       lineinfile: path=/boot/config.txt line='dtparam=i2c_arm=on' regexp='^dtparam='
