---
- hosts: all
  become: true
  tasks:
     - name: update packates 
       apt: update_cache=yes

     - name: Install mosquitto
       apt: name=mosquitto state=latest
       
     - name: Install mosquitto client
       apt: name=mosquitto-clients state=latest
       
     - name: Install paho-mqtt
       pip: name=paho-mqtt
