---
- hosts: all
  become: true
  tasks:
     - name: update packages 
       apt: update_cache=yes
       
     - name: install espeak
       apt: name=espeak state=latest

command to set volume to max: amixer -D default sset Speaker 100%

